using System.Collections.Generic;
using UnityEngine;

namespace OssieCustomColors
{
    // Generated by CalibrationTools.ExportLutSource(). Do not edit by hand.
    // To regenerate: build with CalibrationTools.cs present, run auto-calibration in-game, press the export key (F7).
    static class LutData
    {
        public static readonly Dictionary<string, Color> Entries = new Dictionary<string, Color>
        {
            // Entries will be populated after calibration. Example format:
            // { "FF0000", new Color(0.812345f, 0.000000f, 0.000000f, 1f) },
        };
    }
}
